FORMAT: 1A
HOST: http://inspitrip.com/

# Inspitrip API
# group Users
Users is a set of APIs for users who are staff

## Users Collection [/users/]

### User List [GET]

+ Response 200 (application/json)

        {
            "count":1,
            "next":null,
            "previous":null,
            "results": [
                {
                    "id": 1,
                    "password": "pbkdf2_sha256$36000$BzUx78U8OjLu$OT+swriwAhhkNBqNwm26obpmlGIBX3NtxZbhwzRQekU=",
                    "last_login": "2017-05-19T09:26:05.131128Z",
                    "is_superuser": true,
                    "email": "nguyen@mail.com",
                    "first_name": null,
                    "last_name": null,
                    "photo": null,
                    "nationality": null,
                    "birthday": null,
                    "gender": null,
                    "title": null,
                    "date_joined": "2017-05-15T08:50:04.494382Z",
                    "last_active": "2017-05-19T09:26:16.343600Z",
                    "social_contact": {},
                    "verified_token": null,
                    "verified_token_start": null,
                    "verified_token_expired": "2017-05-15T08:50:04.494430Z",
                    "is_block": false,
                    "block_reason": null,
                    "is_verified": false,
                    "is_staff": true,
                    "is_active": true,
                    "is_localguide": false,
                    "total_reviews": 0,
                    "rating": 0.0,
                    "tags": [],
                    "phone": null,
                    "warning": 0,
                    "is_ambassador": false,
                    "is_licensed": null,
                    "is_featured": false,
                    "hourly_rate": 0.0,
                    "address": null,
                    "about": null,
                    "description": null,
                    "video": null,
                    "score": 0,
                    "state": "init",
                    "is_old_password": false,
                    "salt": null,
                    "uid": null,
                    "slug": null,
                    "place": null,
                    "groups": [],
                    "user_permissions": []
                }
            ]
        }

### Create a new User [POST]

+ Request (application/json)

        {
            "email": "nguyen@mail.com",
            "password": "nguyendeptrai",
            "first_name": "Cheo",
            "last_name": "Dao",
            "last_login": null,
            "is_superuser": true,
            "photo": null,
            "nationality": "VC",
            "birthday": null,
            "gender": "female",
            "title": "pro guide",
            "date_joined": null,
            "last_active": null,
            "social_contact": {},
            "verified_token": null,
            "verified_token_start": null,
            "verified_token_expired": null,
            "is_block": false,
            "block_reason": null,
            "is_verified": false,
            "is_staff": true,
            "is_active": true,
            "is_localguide": false,
            "total_reviews": 0,
            "rating": 0.0,
            "tags": [],
            "phone": null,
            "warning": 0,
            "is_ambassador": false,
            "is_licensed": null,
            "is_featured": false,
            "hourly_rate": 0.0,
            "address": "The authentication that comes with Django is good enough for most common cases",
            "about": "abcxyz",
            "description": "abcxyz",
            "video": null,
            "score": 0,
            "state": "init",
            "is_old_password": false,
            "salt": null,
            "uid": null,
            "slug": null,
            "place": null,
            "groups": [],
            "user_permissions": []
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/2

    + Body

            {
                  "id": 2,
                  "password": "",
                  "last_login": null,
                  "is_superuser": false,
                  "email": "",
                  "first_name": "Nguyen",
                  "last_name": "Dao",
                  "photo": null,
                  "nationality": "VietNam",
                  "birthday": null,
                  "gender": "male",
                  "title": "professional guide",
                  "date_joined": "2017-05-19T10:56:16.072097Z",
                  "last_active": null,
                  "social_contact": {},
                  "verified_token": null,
                  "verified_token_start": null,
                  "verified_token_expired": "2017-05-19T10:56:16.072151Z",
                  "is_block": false,
                  "block_reason": null,
                  "is_verified": false,
                  "is_staff": false,
                  "is_active": false,
                  "is_localguide": false,
                  "total_reviews": 4,
                  "rating": "4.5",
                  "tags": [],
                  "phone": "13256456464",
                  "warning": 0,
                  "is_ambassador": false,
                  "is_licensed": null,
                  "is_featured": false,
                  "hourly_rate": "10",
                  "address": "44 Le Duan, Quan 13, Tp HCM",
                  "about": "Song noi tam, yeu mau tim, thich ... 1 minh",
                  "description": "Dep trai vo dich khap vu tru",
                  "video": null,
                  "score": 0,
                  "state": "init",
                  "is_old_password": false,
                  "salt": null,
                  "uid": null,
                  "slug": null,
                  "place": null,
                  "groups": [],
                  "user_permissions": []
            }
            
## User Detail [/users/{id}/]

+ Parameters
    + id (number) - ID of the User in the form of an integer


### Get a specific User [GET]

+ Response 200 (application/json)

        {
            "id": 2,
            "password": "",
            "last_login": null,
            "is_superuser": false,
            "email": "",
            "first_name": null,
            "last_name": null,
            "photo": null,
            "nationality": null,
            "birthday": null,
            "gender": null,
            "title": null,
            "date_joined": "2017-05-19T10:56:16.072097Z",
            "last_active": null,
            "social_contact": {},
            "verified_token": null,
            "verified_token_start": null,
            "verified_token_expired": "2017-05-19T10:56:16.072151Z",
            "is_block": false,
            "block_reason": null,
            "is_verified": false,
            "is_staff": false,
            "is_active": false,
            "is_localguide": false,
            "total_reviews": 0,
            "rating": 0,
            "tags": [],
            "phone": null,
            "warning": 0,
            "is_ambassador": false,
            "is_licensed": null,
            "is_featured": false,
            "hourly_rate": 0,
            "address": null,
            "about": null,
            "description": null,
            "video": null,
            "score": 0,
            "state": "init",
            "is_old_password": false,
            "salt": null,
            "uid": null,
            "slug": null,
            "place": null,
            "groups": [],
            "user_permissions": []
        }
        
### Update a specific User [PUT]

+ Request (application/json)

        {
            "title": "guide",
            "first_name": "Anh",
            "last_name": "Nguyen",
            "phone": "0654987332",
            "hourly_rate": "10.00",
            "is_staff": true,
            "address": "Dao Duy Tu, Quan 10, Tp HCM",
            "about": "Full service",
            "description": "Professional services",
            "is_localguide": true,
        }
        
+ Response 200 (application/json)

        {
            "id": 2,
            "password": "",
            "last_login": null,
            "is_superuser": false,
            "email": "",
            "first_name": "cheodao",
            "last_name": "dao",
            "photo": null,
            "nationality": null,
            "birthday": null,
            "gender": null,
            "title": "Professional guide",
            "date_joined": "2017-05-19T10:56:16.072097Z",
            "last_active": null,
            "social_contact": {},
            "verified_token": null,
            "verified_token_start": null,
            "verified_token_expired": "2017-05-19T10:56:16.072151Z",
            "is_block": false,
            "block_reason": null,
            "is_verified": false,
            "is_staff": "true",
            "is_active": false,
            "is_localguide": true,
            "total_reviews": 0,
            "rating": 0,
            "tags": [],
            "phone": "12342342342",
            "warning": 0,
            "is_ambassador": false,
            "is_licensed": null,
            "is_featured": false,
            "hourly_rate": "10.00",
            "address": "Dao Duy Tu, Quan 10, Tp HCM",
            "about": "Full service",
            "description": null,
            "video": null,
            "score": 0,
            "state": "init",
            "is_old_password": false,
            "salt": null,
            "uid": null,
            "slug": "cheodao-dao",
            "place": null,
            "groups": [],
            "user_permissions": []
        }

### Delete a specific User [DELETE]

+ Response 204 

# group Locals

## Locals Collection [/locals/]

### Local List [GET]

+ Response 200 (application/json)
        
        {
            "count": 1,
            "next": null,
            "previous": null,
            "results": [
                {
                    "id": 6,
                    "password": "",
                    "last_login": null,
                    "is_superuser": false,
                    "email": "",
                    "first_name": null,
                    "last_name": null,
                    "photo": null,
                    "nationality": null,
                    "birthday": null,
                    "gender": null,
                    "title": null,
                    "social_contact": {},
                    "tags": [],
                    "phone": null,
                    "warning": 0,
                    "hourly_rate": 0,
                    "address": null,
                    "about": null,
                    "description": null,
                    "video": null,
                    "score": 0,
                    "state": "init",
                    "is_old_password": false,
                    "salt": null,
                    "uid": null,
                    "slug": "",
                    "place": null,
                    "groups": [],
                    "user_permissions": []
                }
            ]
        }
        

### Create a new Local [POST]

+ Request (application/json)

        {
            "email": "nguyen.dao@inspilab.com",
            "password": "asdfasdfasdf",
            "first_name": "Nguyen",
            "last_name": "Dao"
        }
        
+ Response 201 (application/json)

    + Headers
        
                Location: /locals/2/
                
    + Body
                
                {
                    "id": 7,
                    "password": "asdfasdfasdf",
                    "last_login": null,
                    "is_superuser": false,
                    "email": "nguyen@inspilab.com",
                    "first_name": "cheodao",
                    "last_name": "dao",
                    "photo": null,
                    "nationality": "Laos",
                    "birthday": null,
                    "gender": ,
                    "title": "professional guide",
                    "social_contact": {},
                    "tags": [],
                    "phone": null,
                    "warning": 0,
                    "hourly_rate": "10.00",
                    "address": "Quan 10, Tp HCM",
                    "about": "to your projects needs involves understanding what points",
                    "description": "to your projects needs involves understanding what points",
                    "video": null,
                    "score": 0,
                    "state": "init",
                    "is_old_password": false,
                    "salt": null,
                    "uid": null,
                    "slug": null,
                    "place": null,
                    "groups": [],
                    "user_permissions": []
                }

                
## Local Detail [/locals/{id}/]

+ Parameters
    + id (number) - ID of the User in the form of an integer

### Get a specific Local [GET]

+ Response 200 (application/json)

        {
            "first_name": "cheodao",
            "last_name": "dao",
            "photo": null,
            "nationality": "Thailand",
            "birthday": null,
            "gender": "male",
            "title": "professional guide",
            "place": null,
            "social_contact": {},
            "tags": [],
            "phone": "012354798",
            "hourly_rate": "10.00",
            "address": "123 Pasteur Quan 1 HCM,
            "about": "The authentication that comes with Django is good enough for most common cases",
            "description": "to your projects needs involves understanding what points ",
            "video": null,
            "state": "init"
        }

### Update a specific Local [PUT]

+ Request (application/json)

        {
            "email": "nguyen@mail.com",
            "password": "nguyendeptrai",
            "first_name": "Cheo",
            "last_name": "Dao",
        }

+ Response 200 (application/json)

        {
            "email": "nguyen@mail.com",
            "password": "asdfasdfasdf",
            "first_name": "Anh Nguyen Dao",
            "last_name": "Dao Anh",
            "photo": null,
            "nationality": null,
            "birthday": null,
            "gender": null,
            "title": null,
            "place": null,
            "social_contact": {},
            "tags": [],
            "phone": null,
            "hourly_rate": 0,
            "address": "Dao Duy Tu",
            "about": "Full service",
            "description": null,
            "video": null,
            "state": "init"
        }
        
        
# group Booking 

## Booking Request [/bookingrequests/]

### Create Booking Request [POST]

+  Request (application/json)

        {
            "email": "nguyen@mail.com",
            "first_name": "Nguyen",
            "last_name": "Dao",
            "booking_dates": "2017-05-19T10:56:16.072097Z",
            "participants": 4,
            "total_hours": 10,
            "message": "Hello cho xin vai do",
            "discount_code": "DM123AHIHI",
            "actual_cost": 100,
            "booking_fee": 20,
            "total_cost": 120,
            "payment_status": "PAID"
        }

+ Response 201 (application/json)

    + Headers

            Location: /bookingrequests/2

    + Body

            {
                  "id": 2,
                  "booking_status": "PENDING",
                  "traveller": 32,
                  "local_insider": 33
            }