# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_snder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='rcver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
