# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170411_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='rcver',
        ),
        migrations.AlterField(
            model_name='message',
            name='snder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
